# Generated by Django 4.2.2 on 2023-07-03 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_statusmodel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
        ('tasks', '0003_alter_tasksmodel_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='label_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='label_id', to='labels.labelmodel'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='executor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_id', to='statuses.statusmodel'),
        ),
    ]
