# Generated by Django 4.2.2 on 2023-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks',
         '0004_tasksmodel_label_id_alter_tasksmodel_author_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksmodel',
            name='label_id',
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='label_id',
            field=models.ManyToManyField(to='labels.labelmodel'),
        ),
    ]
