# Generated by Django 4.2.2 on 2023-07-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tasksmodel_label_id_tasksmodel_label_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='label_id',
            new_name='label',
        ),
    ]
