# Generated by Django 4.2.2 on 2023-07-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_label_id_tasksmodel_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='label',
            new_name='labels',
        ),
    ]
