# Generated by Django 4.2.2 on 2023-07-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_label_tasksmodel_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='executor_id',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='status_id',
            new_name='status',
        ),
    ]
