# Generated by Django 4.2.2 on 2023-06-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='user_id',
        ),
    ]
