# Generated by Django 4.2.2 on 2023-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_remove_statusmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
