# Generated by Django 4.2.2 on 2023-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_statusmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='name',
            field=models.CharField(error_messages={'unique': 'Это имя уже существует.'}, max_length=100, unique=True),
        ),
    ]
